### ISSUE TITLE
babao: command not found

### ISSUE THREAD

**Issue by ghost** [JeanMax/babao#1]
Hi, How can I run the bot? I installed through make, pip as well as setup.py and still getting command not found error.

canermac-3:babao apple$ babao --help
-bash: babao: command not found
canermac-3:babao apple$ babao
-bash: babao: command not found
canermac-3:babao apple$ babao --f
-bash: babao: command not found
You have new mail in /var/mail/apple
canermac-3:babao apple$ babao fetch
-bash: babao: command not found
canermac-3:babao apple$ babao --fetch

looks like it's working only when I run 
python3 -mbabao f

**Comment by JeanMax** [comment]
Hello!

The "binary" should be in your default python bin directory (the user one).
In my case it is: ~/.local/bin/
Maybe you don't have it in your PATH?

Worst case scenario, the make command created a wrapper in the cloned directory: ./babao

**Comment by JeanMax** [comment]
I assume it's "solved". Feel free to re-open the issue.
